

BEGIN TRAN

	BEGIN TRY

	DECLARE @CREATIONUSERIDENTIFIER		NVARCHAR(150)
	DECLARE @CREATIONTIMESTAMP			DATETIME = GETUTCDATE()
	DECLARE @PNROUTPUTITEMID			INT
	DECLARE @PNROUTPUTGROUPID			INT	
	DECLARE @PNROUTPUTGROUPIDCA 		INT
	DECLARE @PNROUTPUTREMARKGROUPID		INT

	SET @CREATIONUSERIDENTIFIER	 = 'Amadeus CA Migration - US17417'
		
	SET @PNROUTPUTITEMID =	(SELECT MAX(PNROUTPUTITEMID)  FROM PNROUTPUTITEM)
	SET @PNROUTPUTGROUPID = (SELECT PNROUTPUTGROUPID FROM PNROUTPUTGROUP WHERE PNROUTPUTGROUPNAME = 'CANADA MIGRATION GENERAL GROUP')
		 
	PRINT 'BEGIN ROLLBACK Amadeus CA Migration - US17417'
		
	---Rollback --
	DELETE FROM PNROUTPUTPLACEHOLDER WHERE CREATIONUSERIDENTIFIER = @CREATIONUSERIDENTIFIER
	DELETE FROM PNROUTPUTGROUPPNROUTPUTITEM WHERE CREATIONUSERIDENTIFIER = @CREATIONUSERIDENTIFIER	
	DELETE FROM PNROUTPUTITEM WHERE CREATIONUSERIDENTIFIER = @CREATIONUSERIDENTIFIER	
	
	PRINT 'END ROLLBACK Amadeus CA Migration - US17417'
	PRINT 'BEGIN INSERT Amadeus CA Migration - US17417'

		INSERT INTO [DBO].[PNROUTPUTPLACEHOLDER]([PNROUTPUTPLACEHOLDERNAME],[PNROUTPUTPLACEHOLDERREGULAREXPRESSSION],[CREATIONTIMESTAMP],[CREATIONUSERIDENTIFIER],[VERSIONNUMBER])
		VALUES		('%ExchangeSequenceNumber%', '(.*)', @CREATIONTIMESTAMP, @CREATIONUSERIDENTIFIER, '1')

		INSERT INTO [DBO].[PNROUTPUTITEM]	([PNROUTPUTITEMID],[PNROUTPUTREMARKTYPECODE], [PNROUTPUTUPDATETYPECODE],[GDSREMARKQUALIFIER],[REMARKFORMAT],PNROUTPUTBINDINGTYPECODE,[CREATIONTIMESTAMP],[CREATIONUSERIDENTIFIER],[VERSIONNUMBER],[PNROUTPUTITEMDEFAULTLANGUAGECODE],[PNROUTPUTITEMXMLFORMAT])
		VALUES								(@PNROUTPUTITEMID + 1,0,1,'T','TKT%ExchangeSequenceNumber%-EXCH',0,@CREATIONTIMESTAMP,@CREATIONUSERIDENTIFIER,1,'en-GB',NULL)
								       
		INSERT INTO [DBO].[PNROUTPUTGROUPPNROUTPUTITEM]	([PNROUTPUTGROUPID],[PNROUTPUTITEMID],[SEQUENCENUMBER],[CREATIONTIMESTAMP],[CREATIONUSERIDENTIFIER],[VERSIONNUMBER],[DATASTANDARDIZATIONVERSION],[LAYOUTVERSION])     
		VALUES											(@PNROUTPUTGROUPID, @PNROUTPUTITEMID + 1,0,@CREATIONTIMESTAMP,@CREATIONUSERIDENTIFIER,1,'1','1')
		
	PRINT 'END UPDATE Amadeus CA Migration - US17417' 
	COMMIT TRAN
	--ROLLBACK TRAN

END TRY
BEGIN CATCH

	ROLLBACK TRAN

	PRINT 'ERROR OCCURRED! Rolled back transactions if there are any:' 
    PRINT ERROR_NUMBER() 
       PRINT 'Error Severity: ' 
    PRINT ERROR_SEVERITY() 
       PRINT 'Error State: ' 
    PRINT ERROR_STATE() 
       PRINT 'Error Procedure: ' 
    PRINT ERROR_PROCEDURE() 
       PRINT 'Error Line: ' 
    PRINT ERROR_LINE() 
       PRINT 'Error Message: ' 
    PRINT ERROR_MESSAGE(); 

END CATCH
